name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/actions/pullrequest.yml'
      - '.idea/copyright/*.xml' 
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'Jenkinsfile '
      - 'README.md'
      - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        # See https://github.com/actions/checkout/commits
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Validate Gradle Wrapper
        # See https://github.com/gradle/wrapper-validation-action/commits
        uses: gradle/wrapper-validation-action@v4

        # See https://github.com/actions/setup-java/commits
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          
      - name: Build
        # See https://github.com/gradle/gradle-build-action/commits
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          gradle-home-cache-cleanup: true
          
      - name: Archive artifacts (Geyser Fabric)
        # See https://github.com/actions/upload-artifact/commits
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Fabric
          path: bootstrap/fabric/build/libs/Geyser-Fabric.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Standalone
          path: bootstrap/standalone/build/libs/Geyser-Standalone.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Spigot
          path: bootstrap/spigot/build/libs/Geyser-Spigot.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser BungeeCord
          path: bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Velocity
          path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
          if-no-files-found: error

